"""
Django settings for EthioAdvance project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from dotenv import dotenv_values

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CREDENTIALS = dotenv_values(BASE_DIR / "EthioAdvance/.env") 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x#4kcq!oj1ta@e5ip5(=)-0phg=ci!g2((ane*ibeyf*iwjs#k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    "accounts.apps.AccountsConfig",
    'parent.apps.ParentConfig',
    'child.apps.ChildConfig',
    'company.apps.CompanyConfig',
    'tutor.apps.TutorConfig',
    'session.apps.SessionConfig',
    'report.apps.ReportConfig',
    'payment.apps.PaymentConfig',
    'django.contrib.humanize',
    'actions.apps.ActionsConfig',
    'testimonials.apps.TestimonialsConfig',
]

SITE_ID = 1  # Usually 1 for the default site

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EthioAdvance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Custom context processor for notification
                'actions.context_processors.notifications_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'EthioAdvance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Loggin Custmization

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'app': {  # Specific logger for this website
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Logout redirect URL
LOGOUT_REDIRECT_URL = 'accounts:home'

# Email server configuration
EMAIL_HOST = CREDENTIALS.get('EMAIL_HOST')
EMAIL_HOST_USER = CREDENTIALS.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = CREDENTIALS.get('EMAIL_HOST_PASSWORD')
EMAIL_PORT = CREDENTIALS.get('EMAIL_PORT')
EMAIL_USE_TLS = bool(CREDENTIALS.get('EMAIL_USE_TLS'))
DEFAULT_FROM_EMAIL = CREDENTIALS.get('DEFAULT_FROM_EMAIL')

# OTP Configuration
OTP_LENGTH = 6  # Length of OTP code
OTP_EXPIRY_MINUTES = 15  # OTP validity in minutes
OTP_RESEND_TIMEOUT = 1  # Minutes before allowing OTP resend

# settings.py
# Minimum required for your OTP flow:
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 3600  # 1 hour expiration
SESSION_SAVE_EVERY_REQUEST = True  # Critical!
SESSION_COOKIE_SECURE = False  # For development, True in production
SESSION_COOKIE_SAMESITE = 'Lax'

# Media configuration
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Session key to store report data during submission
REPORT_KEY = 'report_draft'

# Chapa Configurations
CHAPA_BASE_URL = CREDENTIALS.get('CHAPA_BASE_URL')
CHAPA_PUBLIC_KEY = CREDENTIALS.get('CHAPA_PUBLIC_KEY')
CHAPA_SECRET_KEY = CREDENTIALS.get('CHAPA_SECRET_KEY')
CHAPA_ENCRYPTION_KEY = CREDENTIALS.get('CHAPA_ENCRYPTION_KEY')
CALL_BACK_URL = CREDENTIALS.get('CALL_BACK_URL')
SUCCESS_URL = CREDENTIALS.get('SUCCESS_URL')