# Generated by Django 5.1.7 on 2025-10-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('payment', '0001_initial'),
        ('session', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='payments', to='session.session'),
        ),
        migrations.AddIndex(
            model_name='sessionrate',
            index=models.Index(fields=['updated_at'], name='payment_ses_updated_9e5957_idx'),
        ),
        migrations.AddField(
            model_name='tutorpayments',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_payments', to='child.child'),
        ),
        migrations.AddField(
            model_name='tutorpayments',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='tutor_payments', to='session.session'),
        ),
        migrations.AddField(
            model_name='tutorpayments',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_payments', to='tutor.tutor'),
        ),
        migrations.AddIndex(
            model_name='tutorpayrate',
            index=models.Index(fields=['updated_at'], name='payment_tut_updated_ab6fee_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tx_ref'], name='payment_pay_tx_ref_cc9ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_pay_status_124d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['timestamp'], name='payment_pay_timesta_f18852_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorpayments',
            index=models.Index(fields=['tx_ref'], name='payment_tut_tx_ref_48f9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorpayments',
            index=models.Index(fields=['status'], name='payment_tut_status_6b2495_idx'),
        ),
        migrations.AddIndex(
            model_name='tutorpayments',
            index=models.Index(fields=['timestamp'], name='payment_tut_timesta_87763e_idx'),
        ),
    ]
