# Generated by Django 5.1.7 on 2026-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionrate',
            name='current_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='tutorpayrate',
            name='current_hourly_rate',
        ),
        migrations.AddField(
            model_name='sessionrate',
            name='rate_grade_1_4',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=8),
        ),
        migrations.AddField(
            model_name='sessionrate',
            name='rate_grade_5_8',
            field=models.DecimalField(decimal_places=2, default=600, max_digits=8),
        ),
        migrations.AddField(
            model_name='sessionrate',
            name='rate_grade_9_12',
            field=models.DecimalField(decimal_places=2, default=700, max_digits=8),
        ),
        migrations.AddField(
            model_name='tutorpayrate',
            name='rate_grade_1_4',
            field=models.DecimalField(decimal_places=2, default=350, max_digits=8),
        ),
        migrations.AddField(
            model_name='tutorpayrate',
            name='rate_grade_5_8',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=8),
        ),
        migrations.AddField(
            model_name='tutorpayrate',
            name='rate_grade_9_12',
            field=models.DecimalField(decimal_places=2, default=550, max_digits=8),
        ),
    ]
