# Generated by Django 5.1.7 on 2025-10-28 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the feedback.', verbose_name='Feedback Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the feedback was created.', verbose_name='Created At')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional rating provided by the user (e.g., 1-5 stars).', null=True, verbose_name='Rating')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(help_text='The user who provided the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='feedbacks_f_created_3a98a8_idx')],
            },
        ),
    ]
