# Generated by Django 5.1.7 on 2025-11-01 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '__first__'),
        ('tutor', '__first__'),
    ]

    operations = [

        migrations.CreateModel(
            name='ChallengeEncountered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Challenge Encountered',
                'verbose_name_plural': 'Challenges Encountered',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Learning Material',
                'verbose_name_plural': 'Learning Materials',
            },
        ),
        migrations.CreateModel(
            name='Strength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Strength',
                'verbose_name_plural': 'Strengths',
            },
        ),
        migrations.CreateModel(
            name='SuggestedSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Suggested Solution',
                'verbose_name_plural': 'Suggested Solutions',
            },
        ),
        migrations.CreateModel(
            name='Weakness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Weakness',
                'verbose_name_plural': 'Weaknesses',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('total_sessions_conducted', models.PositiveIntegerField()),
                ('average_duration_per_session', models.DurationField()),
                ('number_of_quizzes_prepared', models.PositiveIntegerField(blank=True, null=True)),
                ('average_quiz_score', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('number_of_mock_exams_prepared', models.PositiveIntegerField()),
                ('mock_exam_result_overview', models.TextField()),
                ('mock_exam_strengths', models.TextField()),
                ('mock_exam_improvement_areas', models.TextField()),
                ('child_participation', models.TextField()),
                ('completion_percentage', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('challenges_encountered', models.ManyToManyField(blank=True, to='report.challengeencountered')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='child.child')),
                ('goals_achieved', models.ManyToManyField(blank=True, to='report.goal')),
                ('learning_material_prepared', models.ManyToManyField(blank=True, to='report.learningmaterial')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='tutor.tutor')),
                ('strengths', models.ManyToManyField(blank=True, to='report.strength')),
                ('suggested_solutions', models.ManyToManyField(blank=True, to='report.suggestedsolution')),
                ('weaknesses', models.ManyToManyField(blank=True, to='report.weakness')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='report_repo_created_be46cb_idx'), models.Index(fields=['tutor'], name='report_repo_tutor_i_39d20d_idx'), models.Index(fields=['child'], name='report_repo_child_i_1809f3_idx')],
            },
        ),
    ]
