# Generated by Django 5.1.7 on 2025-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
