# Generated by Django 5.1.7 on 2025-10-28 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(db_index=True, help_text="Action verb (e.g., 'session.approved', 'payment.received')", max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the main object', null=True)),
                ('links', models.JSONField(blank=True, help_text='URLs to redirect based on role to when this notification is clicked.', null=True, verbose_name='Link')),
                ('type', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', help_text='Type of notification', max_length=10)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional context data in JSON format')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(blank=True, help_text='Related child (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='child.child')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the main object this notification is about', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('delivered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='actions.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Description of the action performed.', max_length=500, verbose_name='Action')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True, verbose_name='Object ID')),
                ('link', models.CharField(blank=True, help_text='A URL to redirect to when this action is clicked.', max_length=500, null=True, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the action was performed.', verbose_name='Timestamp')),
                ('content_type', models.ForeignKey(blank=True, help_text='The type of the related object.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(help_text='The user who performed the action.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='actions_act_user_id_d88e99_idx'), models.Index(fields=['content_type', 'object_id'], name='actions_act_content_ee2b33_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['content_type', 'object_id'], name='actions_not_content_b8f13f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['verb'], name='actions_not_verb_7062de_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user', 'is_read'], name='actions_use_user_id_37a362_idx'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['delivered_at'], name='actions_use_deliver_f52a72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
    ]
