# Generated by Django 5.1.7 on 2025-10-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PARENT', 'Parent'), ('TUTOR', 'Tutor'), ('COMPANY', 'Company')], default='PARENT', max_length=20),
        ),
    ]
