# Generated by Django 5.1.7 on 2026-08-01 16:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2026, 8, 1)), django.core.validators.MinValueValidator(limit_value=datetime.date(1876, 9, 6))]),
        ),
    ]
