# Generated by Django 5.1.7 on 2026-06-06 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('parent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='parentprofile',
            index=models.Index(fields=['company'], name='parent_pare_company_210135_idx'),
        ),
    ]
