# Generated by Django 5.1.7 on 2025-10-28 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the testimonial.', verbose_name='Testimonial Text')),
                ('show_testimonial', models.BooleanField(default=False, help_text='Whether this testimonial should be displayed publicly.', verbose_name='Show Testimonial')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the testimonial was created.', verbose_name='Created At')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Optional rating provided by the parent (e.g., 1-5 stars).', null=True, verbose_name='Rating')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this testimonial should be highlighted as featured.', verbose_name='Featured Testimonial')),
                ('parent', models.ForeignKey(help_text='The parent who provided the testimonial.', on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='parent.parent', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='testimonial_created_f9dacc_idx'), models.Index(fields=['show_testimonial'], name='testimonial_show_te_f4a0f9_idx')],
            },
        ),
    ]
