# Generated by Django 5.1.7 on 2026-06-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child', '0001_initial'),
        ('parent', '0001_initial'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['first_name', 'last_name'], name='child_child_first_n_6545b2_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['grade_level'], name='child_child_grade_l_918f64_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['date_of_birth'], name='child_child_date_of_87dea8_idx'),
        ),
    ]
